---
- name: Main Playbook
  gather_facts: true
  hosts: all
  roles:
    - role: "docker"
    - role: "unifi_ctrl"
    - role: artis3n.tailscale
      vars:
        # manually set env var
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--advertise-routes=10.0.0.0/24"
  tasks:
    - name: Write "Hello World" to the file
      ansible.builtin.copy:
        content: Hello World
        dest: ~/hello.txt
        mode: 0644
