- name: Install dependencies
  become: true
  apt:
    force_apt_get: true
    name:
      - gnupg2
      - software-properties-common

- name: Add Docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker apt repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    filename: docker

- name: Install Docker
  become: true
  apt:
    force_apt_get: true
    name:
      - docker-ce
      - python3-setuptools
      - python3-pip
    install_recommends: false

- name: Install Docker SDK for python
  become: true
  pip:
    name:
      - docker
      - docker-compose

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

- name: Enable Docker IPv6
  become: true
  copy:
    dest: /etc/docker/daemon.json
    mode: 0600
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }
  notify: Restart Docker

- name: Flush handlers
  meta: flush_handlers
